"""Generate experiments/SUMMARY.md (and data used by the website) from the experiment ledgers."""
import glob
import json
import pathlib
import statistics

ROOT = pathlib.Path(__file__).resolve().parents[1]
MANIFEST = json.loads((ROOT / "data" / "eval" / "manifest.json").read_text(encoding="utf-8"))
NAMES = {k: v["language"] for k, v in MANIFEST["pages"].items()}
MIN_PAGE_WORDS = 2000


def load_all():
    recs = []
    a = ROOT / "experiments" / "results.jsonl"
    if a.exists():
        recs += [json.loads(l) for l in a.read_text(encoding="utf-8").splitlines() if l.strip()]
    for f in sorted(glob.glob(str(ROOT / "experiments" / "ledger" / "*.jsonl"))):
        recs += [json.loads(l) for l in pathlib.Path(f).read_text(encoding="utf-8").splitlines() if l.strip()]
    return recs


def by_stage(recs):
    out = {}
    for r in recs:
        out.setdefault(r["stage"], []).append(r)
    return out


def fert(r, l):
    return r["result"]["eval"][l]["fertility"]


def level(r):
    return statistics.mean(fert(r, l) for l in r["langs"])


def best_of(stage_recs):
    """Best balanced record (lowest spread) and the held-out evaluation of those weights."""
    best = min(stage_recs, key=lambda r: r["result"]["spread"])
    held = [r for r in stage_recs if r["result"].get("heldout") and r["weights"] == best["weights"]]
    held = held[-1] if held else next((r for r in reversed(stage_recs) if r["result"].get("heldout")), None)
    return best, held


def akv(r, part="eval"):
    d = r["result"].get(part) or {}
    return sum(v.get("akshara_violations", 0) for v in d.values())


def fourth_rows(stages):
    rows = []
    for st, rs in sorted(stages.items()):
        if not st.startswith("B-") or st == "B-test":
            continue
        best, held = best_of(rs)
        langs = best["langs"]
        x = langs[3] if len(langs) == 4 else "-"
        words = MANIFEST["pages"][x]["words"] if x != "-" else None
        rows.append({
            "stage": st, "lang": x, "name": NAMES.get(x, "none"), "words": words,
            "eligible": x == "-" or words >= MIN_PAGE_WORDS,
            "level": level(best), "max": best["result"]["max_fertility"], "spread": best["result"]["spread"],
            "heldout": held["result"]["heldout_max"] if held else None,
            "heldout_mean": statistics.mean(held["result"]["heldout"][l]["fertility"] for l in langs) if held else None,
            "runs": len(rs), "best_id": best["id"], "akv_eval": akv(best),
        })
    return rows


def ablation_rows(stages, ref_stage="B-ur"):
    rows = []
    for st, rs in sorted(stages.items()):
        if not (st.startswith("C-") or st == ref_stage):
            continue
        best, held = best_of(rs)
        rows.append({
            "stage": st, "level": level(best), "max": best["result"]["max_fertility"],
            "spread": best["result"]["spread"],
            "heldout": held["result"]["heldout_max"] if held else None,
            "akv_eval": akv(best), "akv_heldout": akv(held, "heldout") if held else None,
            "runs": len(rs), "best_id": best["id"], "config": best["config"], "weights": best["weights"],
            "chars": best["info"]["n_base_chars"], "stage1": best["info"]["n_stage1"],
            "learned": best["info"]["n_learned"],
        })
    return rows


def md_table(rows, cols):
    head = "| " + " | ".join(c[1] for c in cols) + " |\n|" + "---|" * len(cols) + "\n"
    body = ""
    for r in rows:
        cells = []
        for key, _, f in cols:
            v = r.get(key)
            cells.append("—" if v is None else (f.format(v) if f else str(v)))
        body += "| " + " | ".join(cells) + " |\n"
    return head + body


if __name__ == "__main__":
    recs = load_all()
    stages = by_stage(recs)
    out = ["# Experiment summary (generated by src/summarize.py — do not edit by hand)\n",
           f"Training runs in the ledgers: **{len(recs)}** "
           f"({len({r['tokenizer_sha256'] for r in recs})} distinct tokenizers)\n"]
    fr = sorted(fourth_rows(stages), key=lambda r: r["level"])
    out.append("## Stage B — fourth-language comparison (same recipe, weights balanced)\n")
    out.append(md_table(fr, [("name", "4th language", None), ("words", "page words", "{:,}"),
                             ("eligible", f"page ≥ {MIN_PAGE_WORDS} words", None),
                             ("level", "mean fertility", "{:.4f}"), ("max", "worst language", "{:.4f}"),
                             ("spread", "spread reached", "{:.5f}"),
                             ("heldout", "held-out worst", "{:.3f}"), ("heldout_mean", "held-out mean", "{:.3f}"),
                             ("akv_eval", "akshara cuts (eval)", None), ("runs", "runs", None),
                             ("best_id", "best run", None)]))
    ab = sorted(ablation_rows(stages), key=lambda r: r["level"])
    if ab:
        out.append("\n## Stage C — recipe ablations on en/hi/te/ur (each re-balanced)\n")
        out.append(md_table(ab, [("stage", "run", None), ("level", "mean fertility", "{:.4f}"),
                                 ("max", "worst language", "{:.4f}"),
                                 ("spread", "spread", "{:.5f}"), ("heldout", "held-out worst", "{:.3f}"),
                                 ("akv_eval", "akshara cuts eval", None), ("akv_heldout", "akshara cuts held-out", None),
                                 ("chars", "chars", None), ("stage1", "akshara tokens", None),
                                 ("learned", "learned merges", None), ("runs", "runs", None)]))
    (ROOT / "experiments" / "SUMMARY.md").write_text("\n".join(out), encoding="utf-8", newline="\n")
    print("\n".join(out))
